/* KTV lyrics auto lookup: LRCLIB public CORS API; no site scraping. */
(()=>{'use strict';const $=id=>document.getElementById(id);if(!$('ktvLyricsFind'))return;
let lines=[],start=0,candidates=[],currentTitle='',currentArtist='',lastKey='',ytSeconds=null,ytUpdated=0,approvedKey='',searchToken=0,sourceSynchronized=false;
let currentVideoId='';
const offsetStoreKey='ktv-lyrics-video-offset-v1';
const lineStoreKey='ktv-lyrics-line-corrections-v1';
let rowAdjustments={},lyricsFingerprint='';
const stamp=t=>Number.isFinite(t)?Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')+'.'+String(Math.round(t%1*10)):'--';
function fingerprint(t){let h=2166136261;for(let i=0;i<t.length;i++){h=Math.imul(h^t.charCodeAt(i),16777619)}return (h>>>0).toString(36)}
function lineKey(){return perVideoKey()+':'+lyricsFingerprint}
function loadLines(){rowAdjustments={};try{const data=JSON.parse(localStorage.getItem(lineStoreKey)||'{}');rowAdjustments=data[lineKey()]||{}}catch(e){}renderLineEditor()}
function saveLines(){try{const data=JSON.parse(localStorage.getItem(lineStoreKey)||'{}');data[lineKey()]={...rowAdjustments};const keys=Object.keys(data);while(keys.length>120){delete data[keys.shift()]}localStorage.setItem(lineStoreKey,JSON.stringify(data))}catch(e){status('逐行校正已套用，但無法存入此瀏覽器。')}}
function calibrated(row,index){return row.time===null?null:Math.max(0,row.time+(Number(rowAdjustments[index])||0))}
function activeLine(){const idx=Number($('ktvLineSelect')?.value);return $('ktvLineSelect')?.value!==''&&Number.isInteger(idx)&&lines[idx]?.time!==null?idx:-1}
function renderLineEditor(){const sel=$('ktvLineSelect');if(!sel)return;const prior=sel.value;sel.replaceChildren(new Option('選取要校正的歌詞',''));lines.forEach((r,i)=>{if(r.time!==null)sel.add(new Option(stamp(calibrated(r,i))+'　'+r.text.slice(0,45),String(i)))});if([...sel.options].some(o=>o.value===prior))sel.value=prior;showLineTime()}
function showLineTime(){const i=activeLine(),t=$('ktvLineTimeStatus');if(!t)return;t.textContent=i<0?'請先選擇含時間標記的歌詞行':'原始 '+stamp(lines[i].time)+' ｜ 校正 '+stamp(calibrated(lines[i],i))+' ｜ 調整 '+((rowAdjustments[i]||0)>0?'+':'')+(Number(rowAdjustments[i])||0).toFixed(1)+' 秒'}
function adjustLine(delta){const i=activeLine();if(i<0)return;rowAdjustments[i]=Math.round(Math.max(-120,Math.min(120,(Number(rowAdjustments[i])||0)+delta))*10)/10;saveLines();renderLineEditor();$('ktvLineSelect').value=String(i);showLineTime()}
function playbackTime(){return ytSeconds!==null&&performance.now()-ytUpdated<2000?ytSeconds:null}
$('ktvLineSelect')?.addEventListener('change',showLineTime);
$('ktvLineEarlier')?.addEventListener('click',()=>adjustLine(-.5));
$('ktvLineLater')?.addEventListener('click',()=>adjustLine(.5));
$('ktvLineUndo')?.addEventListener('click',()=>{const i=activeLine();if(i<0)return;delete rowAdjustments[i];saveLines();renderLineEditor();$('ktvLineSelect').value=String(i);showLineTime()});
$('ktvLineAlign')?.addEventListener('click',()=>{const i=activeLine(),now=playbackTime();if(i<0)return;if(now===null){status('⚠️ 尚未取得 YouTube 可靠的播放時間，不能自動對齊。');return}const offset=Number($('ktvLyricsOffset').value)||0;rowAdjustments[i]=Math.round(Math.max(-120,Math.min(120,now-offset-lines[i].time))*10)/10;saveLines();renderLineEditor();$('ktvLineSelect').value=String(i);showLineTime()});
$('ktvLineResetAll')?.addEventListener('click',()=>{if(!window.confirm('清除此影片與目前歌詞的所有逐行校正？'))return;rowAdjustments={};saveLines();renderLineEditor()});

function perVideoKey(){return currentVideoId ? 'youtube:'+currentVideoId : 'song:'+norm(currentTitle+' '+currentArtist)}
function loadOffset(){let value=0;try{const store=JSON.parse(localStorage.getItem(offsetStoreKey)||'{}');value=Number(store[perVideoKey()]||0)}catch(e){}$('ktvLyricsOffset').value=String(Math.max(-90,Math.min(90,value)));displayOffset()}
function displayOffset(){let value=Number($('ktvLyricsOffset').value||0);if(!Number.isFinite(value))value=0;const label=(value>0?'+':'')+value.toFixed(1)+'s';if($('ktvLyricOffsetLabel'))$('ktvLyricOffsetLabel').textContent='偏移 '+label;if($('ktvLyricLiveOffset'))$('ktvLyricLiveOffset').textContent='字幕 '+label}
function saveOffset(){let value=Number($('ktvLyricsOffset').value||0);if(!Number.isFinite(value))value=0;value=Math.max(-90,Math.min(90,Math.round(value*10)/10));$('ktvLyricsOffset').value=String(value);displayOffset();try{let store=JSON.parse(localStorage.getItem(offsetStoreKey)||'{}');store[perVideoKey()]=value;let keys=Object.keys(store);if(keys.length>200)delete store[keys[0]];localStorage.setItem(offsetStoreKey,JSON.stringify(store))}catch(e){status('字幕偏移已套用，但瀏覽器無法儲存設定。')}}
function shiftOffset(d){$('ktvLyricsOffset').value=String(Number($('ktvLyricsOffset').value||0)+d);saveOffset()}
document.querySelectorAll('[data-lyric-shift]').forEach(b=>b.addEventListener('click',()=>shiftOffset(Number(b.dataset.lyricShift))));
$('ktvLyricReset')?.addEventListener('click',()=>{$('ktvLyricsOffset').value='0';saveOffset()});
$('ktvLyricsOffset').addEventListener('change',saveOffset);displayOffset();
const status=t=>$('ktvLyricsStatus').textContent=t;
const norm=s=>(s||'').toLowerCase().normalize('NFKC').replace(/(?:\(|（|\[|【)[^()（）\[\]【】]*(?:ktv|karaoke|伴奏|官方|mv|lyrics|中字|純音樂)[^()（）\[\]【】]*(?:\)|）|\]|】)/gi,'').replace(/(?:official|music video|karaoke|lyrics|伴奏|官方|高清|完整版)/gi,'').replace(/[^\p{L}\p{N}]+/gu,'').trim();
function parse(t){return (t||'').split(/\r?\n/).flatMap(s=>{let marks=[...s.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\]/g)],txt=s.replace(/\[(\d+):(\d+(?:\.\d+)?)\]/g,'').trim();return marks.length?marks.map(m=>({time:Number(m[1])*60+Number(m[2]),text:txt})):txt&&!/^\[/.test(txt)?[{time:null,text:txt}]:[]}).filter(a=>a.text).sort((a,b)=>(a.time??Infinity)-(b.time??Infinity)).slice(0,500)}
function updateText(t,source='manual'){ $('ktvLyricsText').value=t||'';lines=parse(t);sourceSynchronized=lines.some(v=>v.time!==null);start=performance.now()/1000;const live=$('ktvLyricsLive');live.textContent='';lyricsFingerprint=fingerprint(t||'');loadLines();status(lines.length?'✅ 已載入 '+lines.length+' 行'+(sourceSynchronized?'同步':'靜態')+'歌詞'+(source==='verified'?'（已核對）':'')+'。':'沒有可顯示的歌詞。')}
function current(){if(!lines.length)return '';const now=((ytSeconds!==null&&performance.now()-ytUpdated<2000)?ytSeconds:performance.now()/1000-start)-Number($('ktvLyricsOffset').value||0);if(!sourceSynchronized)return '';let selected='',latest=-Infinity;lines.forEach((row,i)=>{const t=calibrated(row,i);if(t!==null&&t<=now&&t>=latest){latest=t;selected=row.text}});return selected}
function similarity(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return Math.min(a.length,b.length)/Math.max(a.length,b.length)*.82;return 0}
function assess(v,title,artist){const t=similarity(v.trackName,title),a=artist?similarity(v.artistName,artist):0;const duration=window.ktvSongDuration||0,seconds=Number(v.duration)||0;const d=duration&&seconds?Math.abs(duration-seconds):null;const version=/live|cover|翻唱|現場|remix|混音|伴奏|karaoke/i.test((v.trackName||'')+' '+(v.albumName||''));let points=Math.round(t*70+a*25)+(v.syncedLyrics?5:0);if(d!==null&&d>15)points-=d>45?35:15;if(version&&!/live|cover|翻唱|現場|remix|混音/i.test(title))points-=15;return {points,t,a,d,version,verified:t===1&&artist&&a>=.9&&(d===null||d<=15)&&!version&&!!v.syncedLyrics}}
function clearForSong(){approvedKey='';lines=[];sourceSynchronized=false;rowAdjustments={};lyricsFingerprint='';renderLineEditor();$('ktvLyricsText').value='';$('ktvLyricsLive').textContent='';$('ktvLyricsResults').replaceChildren(new Option('尚未核對歌詞',''));}
function draw(ctx,w,h){if(!$('ktvLyricsEnabled').checked)return;const t=current();if(!t)return;ctx.save();ctx.font='bold '+Math.round(w*.039)+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=8;ctx.strokeStyle='rgba(0,0,0,.83)';ctx.fillStyle='#fff';const pieces=Array.from(t);let arr=[],acc='';for(const c of pieces){if(ctx.measureText(acc+c).width>w*.86){arr.push(acc);acc=c;}else acc+=c;}if(acc)arr.push(acc);arr=arr.slice(0,3);arr.forEach((line,i)=>{let y=h*.82+(i-(arr.length-1)/2)*55;ctx.strokeText(line,w/2,y);ctx.fillText(line,w/2,y)});ctx.restore();}
function frame(){const live=$('ktvLyricsLive');if(live&&$('ktvLyricsEnabled').checked)live.textContent=current();else if(live)live.textContent='';setTimeout(frame,160)}frame();
async function lookup(){let title=$('ktvLyricsTitle').value.trim(),artist=$('ktvLyricsArtist').value.trim();if(!title){status('請先播放歌曲或輸入歌名');return;}const token=++searchToken;clearForSong();status('⏳ 正在搜尋並核對歌名、歌手及版本…');$('ktvLyricsFind').disabled=true;try{const q=new URLSearchParams({track_name:title});if(artist)q.set('artist_name',artist);let resp=await fetch('https://lrclib.net/api/search?'+q,{signal:AbortSignal.timeout?AbortSignal.timeout(11000):undefined});if(!resp.ok)throw Error('HTTP '+resp.status);let result=await resp.json();if(!Array.isArray(result)||!result.length){const req=await fetch('https://lrclib.net/api/search?'+new URLSearchParams({q:title+' '+artist}));if(!req.ok)throw Error('HTTP '+req.status);result=await req.json();}if(token!==searchToken)return;candidates=(Array.isArray(result)?result:[]).filter(v=>!v.instrumental&&(v.syncedLyrics||v.plainLyrics)).map(v=>({...v,_match:assess(v,title,artist)})).filter(v=>v._match.t>=.8&&(!artist||v._match.a>=.75)).sort((a,b)=>b._match.points-a._match.points).slice(0,12);const sel=$('ktvLyricsResults');sel.replaceChildren(new Option('請選擇並確認歌詞版本',''));candidates.forEach((v,i)=>sel.add(new Option(v.trackName+' — '+v.artistName+'｜'+(v.syncedLyrics?'同步':'無時間軸')+(v._match.d!==null?'｜長度差 '+Math.round(v._match.d)+'秒':''),String(i))));const safe=candidates.filter(v=>v._match.verified);if(safe.length===1&&candidates[0]===safe[0]&&(candidates.length===1||candidates[0]._match.points-candidates[1]._match.points>=15)){sel.value='0';approve(0,true);}else if(candidates.length){status('⚠️ 找到 '+candidates.length+' 個候選。為避免 A 歌配到 B 歌，請核對歌名／歌手後點「確認使用此歌詞」。');}else status('⚠️ 沒有通過歌名與歌手核對的歌詞，已停止自動顯示。可匯入 LRC。');}catch(e){if(token===searchToken)status('搜尋失敗：'+e.message+'。可以匯入 LRC。')}finally{if(token===searchToken)$('ktvLyricsFind').disabled=false}}
function approve(index,automatic=false){const v=candidates[index];if(!v)return;const title=$('ktvLyricsTitle').value.trim(),artist=$('ktvLyricsArtist').value.trim();const m=assess(v,title,artist);if(m.t<.8||(artist&&m.a<.75)){status('❌ 歌名或歌手不符合，拒絕套用。');return;}if(!automatic&&!m.verified&&!window.confirm('這個版本未通過完整核對，可能歌詞或時間軸不一致。確定要使用「'+v.trackName+' — '+v.artistName+'」嗎？'))return;approvedKey=norm(title+' '+artist);updateText(v.syncedLyrics||v.plainLyrics,'verified');if(!v.syncedLyrics)status('⚠️ 此版本沒有 LRC 時間軸，只能查看文字，不會假裝逐行同步；請匯入同步 LRC。');else if(m.d!==null&&m.d>15)status('⚠️ 已載入同步歌詞，但歌曲長度差 '+Math.round(m.d)+' 秒，請校正字幕偏移。');else status('✅ 已核對 '+v.trackName+' — '+v.artistName+'；'+(automatic?'唯一高信心結果自動套用。':'已確認套用。')+' 請核對實際前奏的字幕時間。')}
$('ktvLyricsFind').addEventListener('click',lookup);
$('ktvLyricsResults').addEventListener('change',()=>status('請確認歌手、歌名、版本，再點「確認使用此歌詞」。'));$('ktvLyricsApprove').addEventListener('click',()=>{const idx=$('ktvLyricsResults').value;if(idx==='')return status('請先選擇候選歌詞');approve(Number(idx))});
$('ktvLyricsText').addEventListener('input',e=>{lines=parse(e.target.value);sourceSynchronized=lines.some(v=>v.time!==null);start=performance.now()/1000;lyricsFingerprint=fingerprint(e.target.value||'');loadLines();});
$('ktvLyricsImport').addEventListener('change',async e=>{const f=e.target.files?.[0];if(f)updateText(await f.text(),'manual')});
$('ktvLyricsQuick').addEventListener('click',()=>{document.getElementById('ktvStudioDetails').open=true;document.getElementById('ktvStudio').classList.add('ktv-settings-open');$('ktvLyricsSettings').scrollIntoView({behavior:'smooth',block:'nearest'})});
window.addEventListener('ktv-song-changed',e=>{const t=e.detail.title||'',a=e.detail.artist||'';currentTitle=t;currentArtist=a;currentVideoId=String(e.detail.videoId||e.detail.id||e.detail.youtubeId||'').trim();loadOffset();searchToken++;clearForSong();ytSeconds=null;ytUpdated=0;$('ktvLyricsTitle').value=t;$('ktvLyricsArtist').value=a;const key=norm(t+' '+a);if(key&&lastKey!==key){lastKey=key;start=performance.now()/1000;lookup()}});
window.addEventListener('message',ev=>{if(ev.origin!=='https://www.youtube.com'||!ev.data)return;try{const obj=typeof ev.data==='string'?JSON.parse(ev.data):ev.data;if(obj?.event==='infoDelivery'&&Number.isFinite(obj.info?.currentTime)){ytSeconds=obj.info.currentTime;ytUpdated=performance.now();}}catch(e){}});
window.ktvLyricsEngine={draw,resetClock:()=>start=performance.now()/1000};
})();
