/* KTV recording studio — local media only; third-party iframe content cannot be captured. */
(function(){'use strict';
const $=id=>document.getElementById(id); const el=$('ktvStudio');if(!el)return;
const canvas=$('studioCanvas'),ctx=canvas.getContext('2d');const stage=$('ktvPlayerStage'),float=$('ktvCamFloat'),preview=$('ktvCamPreview');canvas.width=1280;canvas.height=720;
const video=document.createElement('video'),cam=document.createElement('video'); video.muted=true;video.playsInline=true;video.loop=true;cam.muted=true;cam.playsInline=true;
let camStream=null,micStream=null,screenStream=null,recorder=null,chunks=[],blob=null,blobURL=null,recording=false,raf=0,audioCtx=null,audioDestination=null,sourceNodes=[],startTime=0,overlay={x:.71,y:.57,w:.26},drag=false,library=null,saved=false;
let bgImg=null,bgVideoUrl=null,title='我的 KTV 作品';const status=s=>$('studioStatus').textContent=s;
const mime=()=>{for(const t of ['video/mp4;codecs=h264,aac','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','audio/mp4','audio/webm'])if(MediaRecorder.isTypeSupported(t))return t;return '';};
function drawCover(src){const sw=src.videoWidth||src.naturalWidth,sh=src.videoHeight||src.naturalHeight;if(!sw||!sh)return;const k=Math.max(canvas.width/sw,canvas.height/sh);ctx.drawImage(src,(canvas.width-sw*k)/2,(canvas.height-sh*k)/2,sw*k,sh*k)}
function frame(){const bg=$('studioBackground').value;ctx.fillStyle='#132039';ctx.fillRect(0,0,1280,720);if(bg==='gradient'){const g=ctx.createLinearGradient(0,0,1280,720);g.addColorStop(0,'#151641');g.addColorStop(.5,'#7d2e69');g.addColorStop(1,'#14112e');ctx.fillStyle=g;ctx.fillRect(0,0,1280,720)}else if(bg==='stage'){const g=ctx.createRadialGradient(640,170,20,640,400,850);g.addColorStop(0,'#a35e9d');g.addColorStop(.4,'#39275b');g.addColorStop(1,'#080b1e');ctx.fillStyle=g;ctx.fillRect(0,0,1280,720);for(let i=0;i<7;i++){ctx.strokeStyle='rgba(255,210,255,.13)';ctx.lineWidth=24;ctx.beginPath();ctx.moveTo((i*220)-200,0);ctx.lineTo(640+(i-3)*70,720);ctx.stroke()}}else if(bg==='photo'&&bgImg)drawCover(bgImg);else if(bg==='video'&&video.readyState>=2)drawCover(video);else if(bg==='screen'&&video.readyState>=2)drawCover(video);
if(bg==='camera'&&cam.readyState>=2)drawCover(cam);
if(float&&!float.classList.contains('hidden')&&cam.readyState>=2) {const r=stage.getBoundingClientRect(); if(r.width){float.style.width=(overlay.w*100)+'%';float.style.left=(overlay.x*100)+'%';float.style.top=(overlay.y*100)+'%';}}
if($('studioOverlay').checked&&cam.readyState>=2&&bg!=='camera') {const w=overlay.w*1280,h=w*(cam.videoHeight||720)/(cam.videoWidth||1280),x=overlay.x*1280,y=overlay.y*720;ctx.save();ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,18);else ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(cam,x,y,w,h);ctx.restore();ctx.strokeStyle='#e8c5fa';ctx.lineWidth=4;ctx.strokeRect(x,y,w,h)}
ctx.textAlign='left';ctx.shadowColor='rgba(0,0,0,.75)';ctx.shadowBlur=8;ctx.font='bold 28px sans-serif';ctx.fillStyle='white';ctx.fillText(($('studioTitle').value||'我的 KTV').slice(0,35),26,54);ctx.shadowBlur=0;
if(recording){ctx.fillStyle='#f04468';ctx.beginPath();ctx.arc(1195,42,12,0,Math.PI*2);ctx.fill();ctx.font='24px sans-serif';ctx.fillStyle='white';ctx.fillText(Math.floor((Date.now()-startTime)/1000)+'s',1100,85)}raf=requestAnimationFrame(frame)}
function stopStream(s){if(s)s.getTracks().forEach(t=>t.stop())}
function setMedia(file,type){if(!file)return;const u=URL.createObjectURL(file);if(type==='image'){const im=new Image();im.onload=()=>{bgImg=im};im.src=u}else{if(bgVideoUrl)URL.revokeObjectURL(bgVideoUrl);bgVideoUrl=u;video.src=u;video.play().catch(()=>status('影片已載入；請點擊預覽或播放以啟用影片。'))}}
$('studioPhoto').onchange=e=>{setMedia(e.target.files[0],'image');$('studioBackground').value='photo'};
$('studioVideo').onchange=e=>{setMedia(e.target.files[0],'video');$('studioBackground').value='video'};
$('studioCamera').onclick=async()=>{try{stopStream(camStream);camStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280}},audio:false});cam.srcObject=camStream;preview.srcObject=camStream;await cam.play();await preview.play();float.classList.remove('hidden');$('ktvCamToggle').textContent='📷 關閉鏡頭';$('studioOverlay').checked=true;status('鏡頭已開啟；可以在畫面中拖動人物框，使用大小滑桿調整比例。')}catch(e){status('無法使用鏡頭：'+e.message)}};
$('studioScreen').onclick=async()=>{try{if(!navigator.mediaDevices.getDisplayMedia)throw Error('目前瀏覽器不支援畫面分享錄製');stopStream(screenStream);screenStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});video.srcObject=screenStream;await video.play();$('studioBackground').value='screen';status('已取得畫面分享。僅錄得到瀏覽器允許分享的畫面；系統音效不一定可錄。');screenStream.getVideoTracks()[0].onended=()=>{if(recording)stopRecording()}}catch(e){status('畫面分享無法啟動：'+e.message)}};
$('studioScale').oninput=e=>overlay.w=Number(e.target.value)/100;

$('ktvCamToggle').onclick=async()=>{if(camStream){stopStream(camStream);camStream=null;cam.srcObject=null;preview.srcObject=null;float.classList.add('hidden');$('ktvCamToggle').textContent='📷 開啟鏡頭';return}await $('studioCamera').onclick()};
$('ktvRecordStart').onclick=()=>{if(!camStream){status('尚未開啟鏡頭；請先開啟鏡頭或至錄製設定選擇背景。');$('ktvCamToggle').focus();return}startRecording()};
$('ktvRecordStop').onclick=stopRecording;
$('ktvRecordingOptions').onclick=()=>{$('ktvStudioDetails').open=true;$('ktvStudio').scrollIntoView({behavior:'smooth',block:'start'})};
let pointerId=null,offsetX=0,offsetY=0;
float.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;pointerId=e.pointerId;const r=float.getBoundingClientRect();offsetX=e.clientX-r.left;offsetY=e.clientY-r.top;float.setPointerCapture(e.pointerId);e.preventDefault()});
float.addEventListener('pointermove',e=>{if(pointerId!==e.pointerId)return;const r=stage.getBoundingClientRect(),w=float.getBoundingClientRect().width,h=float.getBoundingClientRect().height;overlay.x=Math.max(0,Math.min((r.width-w)/r.width,(e.clientX-r.left-offsetX)/r.width));overlay.y=Math.max(0,Math.min((r.height-h)/r.height,(e.clientY-r.top-offsetY)/r.height));e.preventDefault()});
float.addEventListener('pointerup',()=>pointerId=null);float.addEventListener('pointercancel',()=>pointerId=null);

canvas.addEventListener('pointerdown',e=>{if(!$('studioOverlay').checked)return;drag=true;canvas.setPointerCapture(e.pointerId);move(e)});canvas.addEventListener('pointermove',e=>{if(drag)move(e)});canvas.addEventListener('pointerup',()=>drag=false);
function move(e){const r=canvas.getBoundingClientRect();overlay.x=Math.max(0,Math.min(1-overlay.w,(e.clientX-r.left)/r.width-overlay.w/2));overlay.y=Math.max(0,Math.min(.8,(e.clientY-r.top)/r.height-.1))}
function connectAudio(stream){if(stream&&stream.getAudioTracks().length){const n=audioCtx.createMediaStreamSource(stream);n.connect(audioDestination);sourceNodes.push(n)}}
function resetResult(){if(blobURL)URL.revokeObjectURL(blobURL);blobURL=null;blob=null;saved=false;$('studioResult').classList.add('studio-hidden');$('studioPlayback').removeAttribute('src');$('studioPlayback').load()}
async function startRecording(){if(recording)return;if(!window.MediaRecorder||!canvas.captureStream){status('本裝置不支援此錄影方式，可改用更新版 Chrome/Edge 或 Safari。');return}try{resetResult();micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});const stream=canvas.captureStream(24);audioCtx=new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume();audioDestination=audioCtx.createMediaStreamDestination();connectAudio(micStream);if(screenStream)connectAudio(screenStream);audioDestination.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const type=mime();recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=e=>status('錄製失敗：'+(e.error?.message||'未知錯誤'));recorder.onstop=()=>{blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'});blobURL=URL.createObjectURL(blob);$('studioPlayback').src=blobURL;$('studioResult').classList.remove('studio-hidden');$('studioRec').disabled=false;$('studioStop').disabled=true;$('ktvRecordStart').disabled=false;$('ktvRecordStop').disabled=true;$('ktvStudioDetails').open=true;$('studioResult').scrollIntoView({behavior:'smooth',block:'center'});status('錄製完成，請先預覽，選擇重唱、儲存或不儲存退出。');cleanupAudio()};recorder.start(1000);recording=true;startTime=Date.now();$('studioRec').disabled=true;$('studioStop').disabled=false;$('ktvRecordStart').disabled=true;$('ktvRecordStop').disabled=false;status('● 正在錄製。提醒：一般 YouTube iframe 的聲音與影像不會自動加入成品，避免使用耳機時只錄到人聲。')}catch(e){cleanupAudio();status('啟動錄製失敗：'+e.message)}}
function cleanupAudio(){stopStream(micStream);micStream=null;sourceNodes.forEach(n=>{try{n.disconnect()}catch(e){}});sourceNodes=[];if(audioCtx)audioCtx.close().catch(()=>{});audioCtx=null}
function stopRecording(){if(!recording)return;recording=false;$('ktvRecordStop').disabled=true;try{if(recorder&&recorder.state!=='inactive')recorder.stop()}catch(e){cleanupAudio();status(e.message)}}
$('studioRec').onclick=startRecording;$('studioStop').onclick=stopRecording;
$('studioRetry').onclick=()=>{resetResult();$('ktvPlayerStage').scrollIntoView({behavior:'smooth',block:'center'});status('已捨棄本次成品，可以重新開始錄製。')};$('studioDiscard').onclick=()=>{resetResult();$('ktvStudioDetails').open=false;status('已放棄本次錄製，沒有儲存。')};
const DB='watch-ktv-records-v1';function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('items',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function transaction(mode,fn){return new Promise(async(resolve,reject)=>{try{const db=await openDB(),tx=db.transaction('items',mode),store=tx.objectStore('items');const req=fn(store);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()}catch(e){reject(e)}})}
function downloadFile(b,name){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
function extension(b){return b.type.includes('mp4')?'mp4':b.type.includes('audio')?'webm':'webm'}
async function saveRecord(){if(!blob)return;const name=($('studioTitle').value||'KTV作品').replace(/[\\/:*?"<>|]/g,'_'),file=name+'_'+new Date().toISOString().replace(/[:.]/g,'-')+'.'+extension(blob);const data={id:Date.now(),name,file,date:new Date().toLocaleString('zh-TW'),size:blob.size,blob};try{await transaction('readwrite',s=>s.put(data));saved=true;downloadFile(blob,file);await renderHistory();status('已儲存在此裝置的瀏覽器作品紀錄，並下載影片。手機請從下載項目使用「分享／儲存影片」存到相簿；並非自動存入相簿。')}catch(e){downloadFile(blob,file);status('已下載影片，但瀏覽器儲存紀錄失敗（空間或私人模式限制）：'+e.message)}}
$('studioSave').onclick=saveRecord;
async function renderHistory(){const wrap=$('studioHistory');try{const records=await transaction('readonly',s=>s.getAll());records.sort((a,b)=>b.id-a.id);wrap.replaceChildren();if(!records.length){wrap.textContent='尚無作品。紀錄存放在此瀏覽器，清除網站資料後可能消失。';return}records.forEach(v=>{const box=document.createElement('div');box.className='studio-history-item';const t=document.createElement('span');t.textContent=v.name+'｜'+v.date+'｜'+(v.size/1048576).toFixed(1)+' MB';const play=document.createElement('button');play.textContent='▶ 預覽';play.onclick=()=>{resetResult();blob=v.blob;blobURL=URL.createObjectURL(blob);$('studioPlayback').src=blobURL;$('studioResult').classList.remove('studio-hidden');$('studioResult').scrollIntoView({behavior:'smooth',block:'nearest'})};const save=document.createElement('button');save.textContent='↓ 再次下載';save.onclick=()=>downloadFile(v.blob,v.file);const del=document.createElement('button');del.textContent='刪除紀錄';del.onclick=async()=>{if(confirm('刪除此瀏覽器的作品及影片備份？不會刪除已下載的影片。')){await transaction('readwrite',s=>s.delete(v.id));renderHistory()}};box.append(t,play,save,del);wrap.appendChild(box)})}catch(e){wrap.textContent='此裝置無法開啟本機作品紀錄：'+e.message}}
$('studioHistoryRefresh').onclick=renderHistory;
$('ktvStudioDetails').addEventListener('toggle',()=>{if($('ktvStudioDetails').open)renderHistory()});
frame();window.addEventListener('pagehide',()=>{stopStream(camStream);stopStream(screenStream);stopStream(micStream);if(raf)cancelAnimationFrame(raf)});
})();
