/* KTV lyrics auto lookup: LRCLIB public CORS API; no site scraping. */
(()=>{'use strict';const $=id=>document.getElementById(id);if(!$('ktvLyricsFind'))return;
let lines=[],start=0,candidates=[],currentTitle='',currentArtist='',lastKey='',ytSeconds=null,ytUpdated=0;
const status=t=>$('ktvLyricsStatus').textContent=t;
const norm=s=>(s||'').toLowerCase().replace(/\([^)]*(ktv|karaoke|伴奏|官方|mv)[^)]*\)/gi,'').replace(/[\[\]【】]/g,'').replace(/\s+/g,' ').trim();
function parse(t){return (t||'').split(/\r?\n/).flatMap(s=>{let marks=[...s.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\]/g)],txt=s.replace(/\[(\d+):(\d+(?:\.\d+)?)\]/g,'').trim();return marks.length?marks.map(m=>({time:Number(m[1])*60+Number(m[2]),text:txt})):txt&&!/^\[/.test(txt)?[{time:null,text:txt}]:[]}).filter(a=>a.text).sort((a,b)=>(a.time??Infinity)-(b.time??Infinity)).slice(0,500)}
function updateText(t){$('ktvLyricsText').value=t||'';lines=parse(t);start=performance.now()/1000;const live=$('ktvLyricsLive');live.textContent='';status(lines.length?'✅ 已載入 '+lines.length+' 行歌詞；同步版本可用秒數偏移調整。':'沒有可顯示的歌詞。')}
function current(){if(!lines.length)return '';let now=((ytSeconds!==null&&performance.now()-ytUpdated<4500)?ytSeconds:performance.now()/1000-start)-Number($('ktvLyricsOffset').value||0);const timed=lines.some(v=>v.time!==null);if(!timed){return lines[Math.min(lines.length-1,Math.max(0,Math.floor(now/4)))]?.text||'';}let selected='';for(const row of lines){if(row.time===null)continue;if(row.time<=now)selected=row.text;else break;}return selected}
function draw(ctx,w,h){if(!$('ktvLyricsEnabled').checked)return;const t=current();if(!t)return;ctx.save();ctx.font='bold '+Math.round(w*.039)+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=8;ctx.strokeStyle='rgba(0,0,0,.83)';ctx.fillStyle='#fff';const pieces=Array.from(t);let arr=[],acc='';for(const c of pieces){if(ctx.measureText(acc+c).width>w*.86){arr.push(acc);acc=c;}else acc+=c;}if(acc)arr.push(acc);arr=arr.slice(0,3);arr.forEach((line,i)=>{let y=h*.82+(i-(arr.length-1)/2)*55;ctx.strokeText(line,w/2,y);ctx.fillText(line,w/2,y)});ctx.restore();}
function frame(){const live=$('ktvLyricsLive');if(live&&$('ktvLyricsEnabled').checked)live.textContent=current();else if(live)live.textContent='';setTimeout(frame,160)}frame();
async function lookup(){let title=$('ktvLyricsTitle').value.trim(),artist=$('ktvLyricsArtist').value.trim();if(!title){status('請先播放歌曲或輸入歌名');return;}status('⏳ 正在查詢公開歌詞資料庫…');$('ktvLyricsFind').disabled=true;try{const q=new URLSearchParams({track_name:title});if(artist)q.set('artist_name',artist);let resp=await fetch('https://lrclib.net/api/search?'+q,{signal:AbortSignal.timeout?AbortSignal.timeout(11000):undefined});if(!resp.ok)throw Error('HTTP '+resp.status);let result=await resp.json();if(!Array.isArray(result)||!result.length){const req=await fetch('https://lrclib.net/api/search?'+new URLSearchParams({q:title+' '+artist}));result=await req.json();}candidates=(Array.isArray(result)?result:[]).filter(v=>!v.instrumental&&(v.syncedLyrics||v.plainLyrics)).sort((a,b)=>{const sc=x=>(norm(x.trackName)===norm(title)?10:0)+(norm(x.artistName)===norm(artist)?5:0)+(x.syncedLyrics?2:0);return sc(b)-sc(a)}).slice(0,12);const sel=$('ktvLyricsResults');sel.replaceChildren(new Option('請選擇符合的歌曲版本',''));candidates.forEach((v,i)=>sel.add(new Option(v.trackName+' — '+v.artistName+(v.syncedLyrics?'（同步）':'（一般）'),String(i))));if(candidates.length){sel.value='0';sel.dispatchEvent(new Event('change'));status('找到 '+candidates.length+' 個結果，已暫選最接近版本；請確認歌手與歌名。');}else status('找不到歌詞；可手動貼上或匯入 LRC。');}catch(e){status('搜尋失敗：'+e.message+'。請確認網路，或匯入 LRC。')}finally{$('ktvLyricsFind').disabled=false}}
$('ktvLyricsFind').addEventListener('click',lookup);
$('ktvLyricsResults').addEventListener('change',e=>{let v=candidates[Number(e.target.value)];if(v)updateText(v.syncedLyrics||v.plainLyrics)});
$('ktvLyricsText').addEventListener('input',e=>{lines=parse(e.target.value);start=performance.now()/1000;});
$('ktvLyricsImport').addEventListener('change',async e=>{const f=e.target.files?.[0];if(f)updateText(await f.text())});
$('ktvLyricsQuick').addEventListener('click',()=>{document.getElementById('ktvStudioDetails').open=true;document.getElementById('ktvStudio').classList.add('ktv-settings-open');$('ktvLyricsSettings').scrollIntoView({behavior:'smooth',block:'nearest'})});
window.addEventListener('ktv-song-changed',e=>{const t=e.detail.title||'',a=e.detail.artist||'';currentTitle=t;currentArtist=a;$('ktvLyricsTitle').value=t;$('ktvLyricsArtist').value=a;const key=norm(t+' '+a);if(key&&lastKey!==key){lastKey=key;start=performance.now()/1000;lookup()}});
window.addEventListener('message',ev=>{if(ev.origin!=='https://www.youtube.com'||!ev.data)return;try{const obj=typeof ev.data==='string'?JSON.parse(ev.data):ev.data;if(obj?.event==='infoDelivery'&&Number.isFinite(obj.info?.currentTime)){ytSeconds=obj.info.currentTime;ytUpdated=performance.now();}}catch(e){}});
window.ktvLyricsEngine={draw,resetClock:()=>start=performance.now()/1000};
})();
